# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dotnetinventoryservice:
    image: dotnetinventoryservice
    build:
      context: .
      dockerfile: src/dotnet.Inventory.Service/Dockerfile
    ports:
      - 5002:5002
